name: Backend CI/CD

on:
  workflow_call:

env:
  ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
  REGION: ${{ secrets.AWS_REGION }}
  CI_PROJECT_BE_NAME: fcjresbar-be
  ECR_REGISTRY_URL_BE: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  ECR_REGISTRY_BE: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.CI_PROJECT_BE_NAME }}
  ECR_REGISTRY_TAG_BE: ${{ github.ref_name }}
  IMAGE_NAME_BE: ${{ env.ECR_REGISTRY_BE }}:${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'backend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        working-directory: ./backend
        run: |
          docker build -f Dockerfile -t ${{ env.IMAGE_NAME_BE }} .
          docker push ${{ env.IMAGE_NAME_BE }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Backend
        run: bash backend/deploy-backend.sh